language: rust

jobs: 
  include: 
    - stage: deploy
      before_script: cargo doc --no-deps
      local-dir: ./target/doc
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      verbose: true
      on:
        branch: master

        #- stage: test 
        # script:
        #- cargo build
        #- cargo test

stages:
  - deploy
