language: rust

script: cargo doc --no-deps

deploy:
  local-dir: ./target/doc
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  verbose: true
  on:
    branch: master


      #- stage: test 
      # script:
      #- cargo build
      #- cargo test

