[package]
name = "flumedb"
version = "0.1.0"
authors = ["Piet Geursen <pietgeursen@gmail.com>"]

[dependencies]
log = "0.4.6"
tokio-codec = "0.1.1"
bytes = "0.4"
byteorder = "1.2.2"
criterion = "0.2.5"
failure = "0.1.3"
pretty_env_logger = "0.2.5"
serde = "1.0.80"
serde-transcode = "1.0.0"
serde_derive = "1.0.80"
serde_json = "1.0.33"

[dependencies.ssb-legacy-msg-data]
path = "../legacy-msg-data"

[dependencies.ssb-legacy-msg]
path = "../ssb-legacy-msg"

[dependencies.ssb-multiformats]
path = "../ssb-multiformats"

[dependencies.rusqlite]
version = "0.15.0"
features = ["bundled", "serde_json", "load_extension"]

[[bench]]
name = "bench"
harness = false
