[package]
name = "flumedb"
version = "0.1.0"
authors = ["Piet Geursen <pietgeursen@gmail.com>"]

[dependencies]
log = "0.4.6"
tokio-codec = "0.1.1"
bincode = "1.0.1"
bytes = "0.4"
bus = "2.0.0"
byteorder = "1.2.2"
criterion = "0.2.5"
failure = "0.1.3"
pretty_env_logger = "0.2.5"
rayon = "1.0.3"
r2d2 = "0.8.3"
r2d2_sqlite = "0.7.0"
serde = "1.0.80"
serde_cbor = "0.9.0"
serde_derive = "1.0.80"
serde_json = "1.0.33"
jsonrpc-core = "9.0.0"
jsonrpc-http-server = "9.0.0"

[dependencies.rusqlite]
version = "0.15.0"
features = ["bundled", "serde_json", "load_extension"]

[[bench]]
name = "bench"
harness = false
