[package]
name = "flumedb"
version = "0.1.0"
authors = ["Piet Geursen <pietgeursen@gmail.com>"]

[dependencies]
tokio = "0.1.6"
tokio-io = "0.1"
tokio-fs = "0.1"
bytes = "0.4"
byteorder = "1.2.2"
serde_json = "1.0.6"
serde = "1.0.21"
serde_derive = "1.0.21"
