[package]
name = "flumedb"
version = "0.1.0"
authors = ["Piet Geursen <pietgeursen@gmail.com>"]

[dependencies]
log = "0.4.6"
tokio = "0.1.6"
tokio-io = "0.1"
tokio-fs = "0.1"
bytes = "0.4"
bus = "2.0.0"
byteorder = "1.2.2"
pretty_env_logger = "0.2.5"
rayon = "1.0.3"
serde_json = "1.0.6"
serde = "1.0.21"
serde_derive = "1.0.21"
bencher = "0.1.5"
jsonrpc-core = "9.0.0"
jsonrpc-http-server = "9.0.0"

[[bench]]
name = "bench"
harness = false
